service: workshop-${self:customer.name}

custom:
  name: serveless-restaurant-workshop

provider:
  name: aws
  runtime: nodejs12.x

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
