service: workshop-${self:custom.name}

custom:
  name: enrique

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get

  get-restaurants:
    handler: functions/get_restaurants.handler
    events:
      - http:
          path: /restaurants
          method: get
    environment:
      restaurants_table: !Ref RestaurantsTable

resources:
  Resources:
    RestaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            AttributeType: HASH
